### ISSUE TITLE
rplanes explorer app catch-up

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/rplanes#118]
while we've been developing the rplanes explorer app we have concurrently been adding new features for v0.0.2. there are several features that we have added that we need to translate into the app:

- [x] weighting scheme (see #107)
- [x] hubverse format option (see #106)
- [x] plane_shape (see #101)
- [x] plane_zero (see #105)
- [x] clean up the overall scoring table 
- [x] render all plots even if not flags raised
- [x] truncate example forecast
- [x] update help page
- [x] fully test the app

**Comment by vpnagraj** [comment]
done via https://github.com/signaturescience/rplanes/pull/121
