### ISSUE TITLE
v0.0.2 release

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/rplanes#119]
opening an issue to track necessary steps ahead of the alpha release (v0.0.1) for the `rplanes` package:

- [x] finish rplanes explorer app catch-up (https://github.com/signaturescience/rplanes/issues/118)
- [x] add improved error handling for locations (https://github.com/signaturescience/rplanes/issues/113)
- [x] review updated individual component vignette (https://github.com/signaturescience/rplanes/issues/104)
- [x] update NEWS
- [x] build and test package across Windows, Mac, Linux platforms with `rhub::check()`
- [x] check test coverage
- [x] review all documentation and examples
- [x] cut release on GitHub Releases tab

**Comment by vpnagraj** [comment]
for code coverage ... the results of `covr::package_coverage()`

```
rplanes Coverage: 87.83%
R/shiny.R: 0.00%
R/utils.R: 75.00%
R/planes.R: 90.50%
R/construct.R: 96.30%
R/seed.R: 100.00%
```

**Comment by vpnagraj** [comment]
for platform checks ... we have checked on the following systems with 0 NOTEs, WARNINGs, or ERRORs:

- Windows Server 2022, R-release, 32/64 bit
- Debian Linux, R-release, GCC
- Fedora Linux, R-devel, clang, gfortran
- Mac OS X (R 4.2.3)

**Comment by vpnagraj** [comment]
released 🚀
