### ISSUE TITLE
v0.0.3 release

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/rplanes#128]
opening an issue to track necessary steps ahead of the alpha release (v0.0.3) for the `rplanes` package:

- [x] typo in README (https://github.com/signaturescience/rplanes/issues/124)
- [x] fix issue with missing data in seed (https://github.com/signaturescience/rplanes/issues/127)
- [x] fix issue with plane_repeat behavior on constant signals (https://github.com/signaturescience/rplanes/issues/130)
- [x] clarify weighting scheme documentation (https://github.com/signaturescience/rplanes/issues/126)
- [x] update NEWS
- [x] ~build and test package across Windows, Mac, Linux platforms with `rhub::check()`~ noting that RHUB was down so the package was built and checked locally and on Linux platforms with the GH Action
- [x] check test coverage
- [x] review all documentation and examples
- [x] cut release on GitHub Releases tab

**Comment by vpnagraj** [comment]
v0.0.3 is now released: https://github.com/signaturescience/rplanes/releases/tag/v0.0.3
